version: '3'

services:
  api:
    build: ./api
    command: npm run start
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - HOST=http://real-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
